version: '3'

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    ports:
      - "4000:4000"
    env_file:
      - .env
  db:
    container_name: db
    image: postgres:15.1-alpine3.17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
      
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    depends_on:
      - db
    env_file:
      - .env


